"use client"

import {useState, useEffect} from 'react'

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Image from "next/image";
import Link from "next/link";
import { MdHomeRepairService } from "react-icons/md"
import { CgMenuLeft } from "react-icons/cg";
import classes from '@/app/style/Nav.module.css'

import AlertContext from '@/app/admin/components/context/AlertContext';
import Alert from '@/app/admin/components/Alert';
import {AlertInterface} from '@/app/admin/components/Interface/AlertInterface';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const [alert, setAlert] = useState<AlertInterface>({
    message: null,
    status: null
  });

  return (
    
    <article className=''>
        <AlertContext.Provider value={{alert, setAlert}}>
        <Alert/>
            {children}
        </AlertContext.Provider>
    </article>
  );
}
