"use client"

import {useState, useEffect, useContext} from 'react'

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Image from "next/image";
import Link from "next/link";

import { useRouter, usePathname } from 'next/navigation';
import { MdHomeRepairService, MdWorkHistory, MdGroupWork, MdContactPhone, MdFeedback, MdOutlineSettings } from "react-icons/md"
import { CgMenuLeft } from "react-icons/cg";
import { FaAddressCard, FaUsers, FaUserGraduate, FaToolbox, FaServicestack, FaDotCircle, FaGlobe } from "react-icons/fa";
import { AiFillInteraction, AiFillProfile } from "react-icons/ai";
import { GiAchievement } from "react-icons/gi";
import { IoMdLogOut } from "react-icons/io";



import classes from '@/app/style/Nav.module.css'
import AlertContext from '@/app/admin/components/context/AlertContext';
import Alert from '@/app/admin/components/Alert';
import {AlertInterface} from '@/app/admin/components/Interface/AlertInterface';

const inter = Inter({ subsets: ["latin"] });
import RequestClass from '@/app/admin/components/requestClass';
import PageLoading from '@/app/components/PageLoading';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();
  const router = useRouter();

  const context = useContext(AlertContext)

  const requestClass = new RequestClass('/api/v1/user/me');

  const [user, setUser] = useState(null)

  useEffect(()=>{
    (async()=>{
      try {
        const res =  await requestClass.getRequest();
        setUser(res.data.user)
      } catch (err: any) {
        if (err.response) {
          console.log(err.response)
          if(context?.alert) {
            context?.setAlert({
              message: err.response.data.message,
              status: err.response.data.status
            })
          }
        } else {
          console.log(err);
        }
        setUser(null)
        router.push('/admin/login')
      } 
    })()
  }, [pathname])


  // ===========LOGOUT=============
  const [loggingOut, setLoggingOut] = useState(false);

  const logRequestClass = new RequestClass('/api/v1/user/auth/signout');

    const logOut = async() => {

        setLoggingOut(true)
        try {
          const res =  await logRequestClass.postRequest();

          if(process.env.NEXT_PUBLIC_ENV === 'development') localStorage.setItem('token', `Bearer ${res.data.token}`)

          if(context?.alert) {
            context?.setAlert({
              message: res.data.message,
              status: res.data.status
            })
          }
          
        //   await fetchTools()
          setLoggingOut(false)
          setUser(null)
          router.push('/admin/login');
        } catch (err: any) {
          if (err.response) {
            if(context?.alert) {
              context?.setAlert({
                message: err.response.data.message,
                status: err.response.data.status
              })
            }
          } else {
            console.log(err);
          }
          setLoggingOut(false)
        } 
    }


  // ==============================
  const [showMenu, setShowMenu] = useState(false)
  let [screenWidth, setScreenWidth] = useState<number | null>(null);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setScreenWidth(window.innerWidth);
      const handleResize = () => {
        setScreenWidth(window.innerWidth);
      };
      window.addEventListener('resize', handleResize);
      return () => {
        window.removeEventListener('resize', handleResize);
      };
    }
  }, []);

  // show mobile menu setter function
  const showMenuHandler = (payload: boolean) => {
    setShowMenu(payload)
  }

  // FOR MOBILE MENU
  useEffect(()=>{
    if (typeof window !== 'undefined' && document.getElementById('menu')) {
      // your code here
      let sideMenu = document.getElementById('menu')
      if(sideMenu) {
        if (showMenu === false && screenWidth! <= 787) {
          sideMenu.style.left = "-101%";
        }else if(showMenu === true && screenWidth! <= 787)  {
          sideMenu.style.left = "0%";
        }
      }
    }
    
  }, [showMenu, screenWidth])

  const navsLinks = [
    {
      href: '/admin/dashboard',
      name: 'Dashboard',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/banner',
      name: 'Banner',
      icon: <FaAddressCard/>
    },
    {
      href: '/admin/dashboard/client',
      name: 'Clients',
      icon: <FaUsers />
    },
    {
      href: '/admin/dashboard/testimonial',
      name: 'Testimonials',
      icon: <MdFeedback />
    },
    {
      href: '/admin/dashboard/cta',
      name: 'CTA',
      icon: <AiFillInteraction/>
    },
    {
      href: '/admin/dashboard/cta-btn',
      name: 'CTA Button',
      icon: <AiFillInteraction/>
    },
    {
      href: '/admin/dashboard/education',
      name: 'Education',
      icon: <FaUserGraduate/>
    },
    {
      href: '/admin/dashboard/experience',
      name: 'Experience',
      icon: <MdWorkHistory />
    },
    {
      href: '/admin/dashboard/tools',
      name: 'Tools',
      icon: <FaToolbox />
    },
    {
      href: '/admin/dashboard/service',
      name: 'Services',
      icon: <FaServicestack />
    },
    {
      href: '/admin/dashboard/achievement',
      name: 'Achievements',
      icon: <GiAchievement />
    },
    {
      href: '/admin/dashboard/portfolio',
      name: 'Portfolio',
      icon: <MdGroupWork />
    },
    {
      href: '/admin/dashboard/contact',
      name: 'Contact',
      icon: <MdContactPhone />
    },
    {
      href: '/admin/dashboard/logo',
      name: 'Logo',
      icon: <FaDotCircle />
    },
    {
      href: '/admin/dashboard/cv',
      name: 'CV',
      icon: <AiFillProfile />
    },
  ]

  const closeMenu = (e: React.MouseEvent<HTMLElement>): void => {
    const target = e.target as HTMLElement;
    if (target.classList.contains('close')) {
      setShowMenu(false);
    }
  };

 

  const [alert, setAlert] = useState<AlertInterface>({
    message: null,
    status: null
  });

  const [showProfile, setShowProfile] = useState(false)

  useEffect(() => {
    function tuggleProfileMenu(e: any) {
      const target = e.target as HTMLElement; 

      if(target.classList.contains('show-profile-menu')) {
        setShowProfile(true)
      } else {
        setShowProfile(false)
      }
    }

    window.addEventListener('click', tuggleProfileMenu);
    return () => {
      window.removeEventListener('resize', tuggleProfileMenu);
    };
  }, []);

  return (
    <>
      {loggingOut && <PageLoading/>}
      {
        user ? (
          <div>
              <aside className={['w-[100%] md:w-[25%] fixed md:block bg-[rgba(0, 0, 0, 0.4)] md:bg-[#333] backdrop-blur-lg bg-black/30 h-screen p-0 close z-10 left-[-101%] md:left-0', classes.menu].join(' ')} id='menu' onClick={closeMenu}>
                <div className='w-[80%] md:w-[100%] bg-[#333] h-screen px-5 py-10 fixed overflow-y-scroll'>
                  {
                      (screenWidth! <= 787) && <button className='bg-transparent rounded-full text-3xl text-red-600 outline-none mb-10 close'>&times;</button>
                  }
                  {
                      navsLinks.map((item, index)=>{
                      return <Link href={item.href} key={index} className='text-white flex gap-3 mb-5 items-center close'>{item.icon} {item.name}</Link>
                      })
                  }
                </div>
              </aside>
              <main className="bg-gray-100 min-h-screen ml-auto md:w-[75%] w-[100%] relative">
                  <header className="bg-white flex w-full px-5 py-2 relative">
                    <nav className="flex md:block justify-between items-center w-full">
                      <CgMenuLeft className='md:hidden text-2xl' onClick={()=>setShowMenu((props)=>!props)}/>
                      <div className='md:ml-auto flex items-center justify-end w-fit gap-3'>
                        <Link href={'/'} className='bg-clip-text text-gray-800 bg-gradient-to-br from-white to-gray-800 text-5xl'><FaGlobe /></Link>
                        <div style={{ position: 'relative', height: '50px', width: '50px' }} className=" rounded-[100px] border border-black ">
                          <Image
                              src={'/images/pic.jpg'}
                              alt="Picture of the author"
                              sizes="100%"
                              fill
                              style={{
                              objectFit: 'cover',
                              }}
                              className='rounded-[100px] show-profile-menu'
                          />
                        </div>
                      </div>
                      <div className={['bg-white shadow-md top-16 right-2 p-4', showProfile ? 'absolute' : 'hidden'].join(' ')}>
                        <ul>
                          <li><Link href={'/admin/dashboard/change-password'} className='text-black flex gap-3 mb-3 items-center text-sm'><MdOutlineSettings /> Change Password</Link></li>
                          <li className='h-[1px] w-full mb-3 bg-gray-200'></li>
                          <li><button className='text-red-500bsi flex gap-3 mb-3 items-center text-sm' onClick={()=>logOut()}><IoMdLogOut/> Logout</button></li>
                        </ul>
                      </div>
                    </nav>
                  </header>
                  <article className='px-[3%] py-10'>
                    <AlertContext.Provider value={{alert, setAlert}}>
                      <Alert/>
                      {children}
                    </AlertContext.Provider>
                  </article>
              </main>  
            </div>
        ) : null
      }
    </>
  );
}
