"use client"

import {useState, useEffect, useContext} from 'react'

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from 'next/navigation';
import { MdHomeRepairService } from "react-icons/md"
import { CgMenuLeft } from "react-icons/cg";


import classes from '@/app/style/Nav.module.css'
import AlertContext from '@/app/admin/components/context/AlertContext';
import Alert from '@/app/admin/components/Alert';
import {AlertInterface} from '@/app/admin/components/Interface/AlertInterface';

const inter = Inter({ subsets: ["latin"] });
import RequestClass from '@/app/admin/components/requestClass';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const router = useRouter();

  const context = useContext(AlertContext)

  const requestClass = new RequestClass('/api/v1/user/me');

  const [user, setUser] = useState(null)

  useEffect(()=>{
    (async()=>{
      try {
        const res =  await requestClass.getRequest();
        setUser(res.data.user)
      } catch (err: any) {
        if (err.response) {
          console.log(err.response)
          if(context?.alert) {
            context?.setAlert({
              message: err.response.data.message,
              status: err.response.data.status
            })
          }
        } else {
          console.log(err);
        }
        router.push('/admin/login')
      } 
    })()
  }, [window.location.pathname])


  // ==============================
    const [showMenu, setShowMenu] = useState(false)
  let [screenWidth, setScreenWidth] = useState<number | null>(null);

  useEffect(() => {
    // Check if window is defined (this will be true only in the browser)
    if (typeof window !== 'undefined') {
      // Set initial window width
      setScreenWidth(window.innerWidth);

      // Define a resize handler
      const handleResize = () => {
        setScreenWidth(window.innerWidth);
      };

      // Add event listener for window resize
      window.addEventListener('resize', handleResize);

      // Clean up event listener on component unmount
      return () => {
        window.removeEventListener('resize', handleResize);
      };
    }
  }, []);

  // show mobile menu setter function
  const showMenuHandler = (payload: boolean) => {
    setShowMenu(payload)
  }

  // FOR MOBILE MENU
  useEffect(()=>{
    
    let sideMenu = document.getElementById('menu')
    if(sideMenu) {
      if (showMenu === false && screenWidth! <= 787) {
        sideMenu.style.left = "-101%";
      }else if(showMenu === true && screenWidth! <= 787)  {
        sideMenu.style.left = "0%";
      }
    }

  }, [showMenu])

  const navsLinks = [
    {
      href: '/admin/dashboard',
      name: 'Dashboard',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/banner',
      name: 'Banner',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/client',
      name: 'Clients',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/testimonial',
      name: 'Testimonials',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/cta',
      name: 'CTA',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/education',
      name: 'Education',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/experience',
      name: 'Experience',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/tools',
      name: 'Tools',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/service',
      name: 'Services',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/achievement',
      name: 'Achievements',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/portfolio',
      name: 'Portfolio',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/contact',
      name: 'Contact',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/logo',
      name: 'Logo',
      icon: <MdHomeRepairService/>
    },
    {
      href: '/admin/dashboard/cv',
      name: 'CV',
      icon: <MdHomeRepairService/>
    },
  ]

  const closeMenu = (e: React.MouseEvent<HTMLElement>): void => {
    const target = e.target as HTMLElement;
    if (target.classList.contains('close')) {
      setShowMenu(false);
    }
  };

 

  const [alert, setAlert] = useState<AlertInterface>({
    message: null,
    status: null
  });

  return (
    user ? (
      <html lang="en">
        <body className={inter.className}>
          <aside className={['w-[100%] md:w-[25%] fixed md:block bg-[rgba(0, 0, 0, 0.4)] md:bg-[#333] backdrop-blur-lg bg-black/30 h-screen p-0 close z-10 left-[-101%] md:left-0', classes.menu].join(' ')} id='menu' onClick={closeMenu}>
          <div className='w-[60%] md:w-[100%] bg-[#333] h-screen px-5 py-10 fixed overflow-y-scroll'>
          {
              (screenWidth! <= 787) && <button className='bg-transparent rounded-full text-3xl text-red-600 outline-none mb-10 close'>&times;</button>
          }
          {
              navsLinks.map((item, index)=>{
              return <Link href={item.href} key={index} className='text-white flex gap-3 mb-5 items-center close'>{item.icon} {item.name}</Link>
              })
          }
          </div>
          </aside>
          <main className="bg-gray-100 min-h-screen ml-auto md:w-[75%] w-[100%] relative">
              <header className="bg-white flex w-full px-5 py-2">
              <nav className="flex md:block justify-between items-center w-full">
                  <CgMenuLeft className='md:hidden text-2xl' onClick={()=>setShowMenu((props)=>!props)}/>
                  <div style={{ position: 'relative', height: '50px', width: '50px' }} className=" rounded-[100px] border border-black  md:ml-auto">
                      <Image
                          src={'/images/pic.jpg'}
                          alt="Picture of the author"
                          sizes="100%"
                          fill
                          style={{
                          objectFit: 'cover',
                          }}
                          className='rounded-[100px]'
                      />
                  </div>
              </nav>
              </header>
              <article className='px-[3%] py-10'>
                <AlertContext.Provider value={{alert, setAlert}}>
                  <Alert/>
                  {children}
                </AlertContext.Provider>
              </article>
          </main>
          
        </body>
      </html>
    ) : null
  );
}
